--------------------------------------------------------
--  File created - Friday-May-31-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLUB_RECORD
--------------------------------------------------------

  CREATE TABLE "FCM"."CLUB_RECORD" 
   (	"CLUB_NAME" VARCHAR2(30 BYTE), 
	"C_TOTAL_GAMES" NUMBER, 
	"C_WINS" NUMBER, 
	"C_LOSES" NUMBER, 
	"C_DRAWS" NUMBER, 
	"C_NO_OF_TITLES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLUB_RECORD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FCM"."CLUB_RECORD_PK" ON "FCM"."CLUB_RECORD" ("CLUB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CLUB_RECORD
--------------------------------------------------------

  ALTER TABLE "FCM"."CLUB_RECORD" ADD CONSTRAINT "CLUB_RECORD_PK" PRIMARY KEY ("CLUB_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "FCM"."CLUB_RECORD" MODIFY ("CLUB_NAME" NOT NULL ENABLE);
