--------------------------------------------------------
--  File created - Friday-May-31-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PLAYER
--------------------------------------------------------

  CREATE TABLE "FCM"."PLAYER" 
   (	"PLAYER_ID" VARCHAR2(20 BYTE), 
	"P_NAME" VARCHAR2(20 BYTE), 
	"P_AGE" NUMBER(2,0), 
	"P_NATIONALITY" VARCHAR2(20 BYTE), 
	"CONTRACT_ID" VARCHAR2(20 BYTE), 
	"AGENT_ID" VARCHAR2(20 BYTE), 
	"CONTACT" NUMBER(15,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PLAYER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FCM"."PLAYER_PK" ON "FCM"."PLAYER" ("PLAYER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PLAYER
--------------------------------------------------------

  ALTER TABLE "FCM"."PLAYER" ADD CONSTRAINT "PLAYER_PK" PRIMARY KEY ("PLAYER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "FCM"."PLAYER" MODIFY ("PLAYER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PLAYER
--------------------------------------------------------

  ALTER TABLE "FCM"."PLAYER" ADD CONSTRAINT "PLAYER_FK3" FOREIGN KEY ("AGENT_ID")
	  REFERENCES "FCM"."AGENT" ("AGENT_ID") ENABLE;
 
  ALTER TABLE "FCM"."PLAYER" ADD CONSTRAINT "PLAYER_FK4" FOREIGN KEY ("CONTRACT_ID")
	  REFERENCES "FCM"."CONTRACT" ("CONTRACT_ID") ENABLE;
