--------------------------------------------------------
--  File created - Friday-May-31-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STADIUM
--------------------------------------------------------

  CREATE TABLE "FCM"."STADIUM" 
   (	"STADIUM_NAME" VARCHAR2(20 BYTE), 
	"CAPACITY" NUMBER, 
	"PITCH_TYPE" VARCHAR2(30 BYTE), 
	"PITCH_PATTERN" VARCHAR2(20 BYTE), 
	"LOCATION_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STADIUM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FCM"."STADIUM_PK" ON "FCM"."STADIUM" ("STADIUM_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table STADIUM
--------------------------------------------------------

  ALTER TABLE "FCM"."STADIUM" ADD CONSTRAINT "STADIUM_PK" PRIMARY KEY ("STADIUM_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "FCM"."STADIUM" MODIFY ("STADIUM_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table STADIUM
--------------------------------------------------------

  ALTER TABLE "FCM"."STADIUM" ADD CONSTRAINT "STADIUM_FK1" FOREIGN KEY ("LOCATION_ID")
	  REFERENCES "FCM"."LOCATION" ("LOCATION_ID") ENABLE;
