--------------------------------------------------------
--  File created - Wednesday-May-29-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table WINNING_YEAR
--------------------------------------------------------

  CREATE TABLE "FCM"."WINNING_YEAR" 
   (	"WIN_YEAR_ID" VARCHAR2(20 BYTE), 
	"YEAR" VARCHAR2(20 BYTE), 
	"COMPETITION_NAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index WINNING_YEAR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FCM"."WINNING_YEAR_PK" ON "FCM"."WINNING_YEAR" ("WIN_YEAR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table WINNING_YEAR
--------------------------------------------------------

  ALTER TABLE "FCM"."WINNING_YEAR" MODIFY ("WIN_YEAR_ID" NOT NULL ENABLE);
 
  ALTER TABLE "FCM"."WINNING_YEAR" ADD CONSTRAINT "WINNING_YEAR_PK" PRIMARY KEY ("WIN_YEAR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
